language: python
dist: xenial
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5
  - 2.7
before_install:
  - pip install --upgrade setuptools pip
install:
  - pip install --upgrade .[cache] pytest-cov
script:
  - pytest --cov pytest_check_links
after_success:
  - pip install codecov
  - codecov
